"""Currículo — Nível Básico módulos 4-6, Intermediário e Avançado."""

BASICO_M4_6 = [
  {
   "order":4,"icon":"🛡️","color":"#10b981","xp_reward":110,
   "title":"Erros, Módulos e Arquivos",
   "description":"Trate erros com try/except. Use módulos da biblioteca padrão. Leia e escreva arquivos CSV e JSON.",
   "lessons":[
    {"order":1,"title":"Try/Except: código que não quebra","reading_minutes":8,
     "content":"Erros são inevitáveis. Arquivos não existem, conexões caem, usuários digitam errado. try/except captura erros e permite tratar graciosamente.",
     "code_example":"# Com tratamento de erro\ntry:\n    numero = int(input('Número: '))\n    resultado = 100 / numero\nexcept ValueError:\n    print('Digite apenas números!')\nexcept ZeroDivisionError:\n    print('Não é possível dividir por zero!')\nexcept Exception as e:\n    print(f'Erro inesperado: {e}')\nelse:\n    print(f'Resultado: {resultado}')  # só se não houve erro\nfinally:\n    print('Fim.')  # sempre executa\n\n# Leitura segura de arquivo\nimport json\ndef ler_config(path):\n    try:\n        with open(path, 'r', encoding='utf-8') as f:\n            return json.load(f)\n    except FileNotFoundError:\n        return {'debug': False, 'porta': 8000}\n    except json.JSONDecodeError as e:\n        print(f'Config inválida: {e}')\n        return {}",
     "real_world_case":"Em produção, um erro não tratado derruba o servidor. Com try/except, o erro é logado e o sistema continua.",
     "best_practice":"Nunca use 'except:' sem tipo — pode silenciar erros graves. Use finally para fechar arquivos e conexões."},
    {"order":2,"title":"CSV e JSON — formatos do backend","reading_minutes":9,
     "content":"CSV é o formato universal de planilhas. JSON é o formato universal de APIs.",
     "code_example":"import csv, json\n\n# CSV — escrever e ler\nfuncs = [{'nome':'Ana','cargo':'Dev','salario':8000}]\nwith open('func.csv','w',newline='',encoding='utf-8') as f:\n    w = csv.DictWriter(f, fieldnames=['nome','cargo','salario'])\n    w.writeheader(); w.writerows(funcs)\n\nwith open('func.csv','r',encoding='utf-8') as f:\n    for row in csv.DictReader(f):\n        print(f\"{row['nome']}: R$ {row['salario']}\")\n\n# JSON — salvar e carregar\nwith open('dados.json','w',encoding='utf-8') as f:\n    json.dump(funcs, f, ensure_ascii=False, indent=2)\n\nwith open('dados.json','r',encoding='utf-8') as f:\n    carregado = json.load(f)\n\n# String ↔ dict\ndct = json.loads('{\"nome\": \"Ana\"}')\ntxt = json.dumps({'nome': 'Ana'}, ensure_ascii=False)",
     "real_world_case":"Toda integração com sistema financeiro usa CSV. Toda API REST usa JSON.",
     "best_practice":"CSV: use DictReader/DictWriter. JSON: use indent=2 para legibilidade. Sempre ensure_ascii=False para acentos."},
   ],
   "exercises":[
    {"order":1,"difficulty":"facil","xp_reward":15,
     "title":"Calculadora Segura",
     "description":"Crie calcular(expressao: str) que receba '10 + 5', '100 / 0', '3 * abc' e retorne {'resultado': valor, 'erro': None} ou {'resultado': None, 'erro': 'mensagem'}.",
     "hint":"Divida com .split(). Converta com float() dentro de try. Trate divisão por zero separadamente.",
     "starter_code":"def calcular(expressao: str) -> dict:\n    try:\n        partes = expressao.strip().split()\n        # valide, converta e calcule\n        pass\n    except Exception as e:\n        return {'resultado': None, 'erro': str(e)}\n\nprint(calcular('10 + 5'))\nprint(calcular('100 / 0'))\nprint(calcular('abc + 5'))\n",
     "solution_hint":"def calcular(expr):\n    try:\n        p=expr.strip().split()\n        if len(p)!=3: raise ValueError('Formato: num op num')\n        a,op,b=float(p[0]),p[1],float(p[2])\n        if op=='+': r=a+b\n        elif op=='-': r=a-b\n        elif op=='*': r=a*b\n        elif op=='/':\n            if b==0: raise ZeroDivisionError('divisão por zero')\n            r=a/b\n        else: raise ValueError(f'Operador {op} desconhecido')\n        return {'resultado':r,'erro':None}\n    except ZeroDivisionError as e: return {'resultado':None,'erro':str(e)}\n    except ValueError as e: return {'resultado':None,'erro':str(e)}"},
    {"order":2,"difficulty":"facil","xp_reward":20,
     "title":"Log de Sistema",
     "description":"Usando datetime, crie:\n- log(nivel, mensagem) com timestamp\n- relatorio_logs() → {'total_por_nivel': dict, 'ultimos_erros': list}",
     "hint":"datetime.datetime.now().strftime('%d/%m/%Y %H:%M:%S'). Use Counter de collections.",
     "starter_code":"import datetime\nfrom collections import Counter\n\nLOGS = []\n\ndef log(nivel, mensagem): pass\ndef relatorio_logs(): pass\n\nlog('INFO', 'Sistema iniciado')\nlog('WARNING', 'Tentativa falhou')\nlog('ERROR', 'Banco desconectado')\nprint(relatorio_logs())\n",
     "solution_hint":"def log(nivel,msg):\n    ts=datetime.datetime.now().strftime('%d/%m/%Y %H:%M:%S')\n    LOGS.append({'nivel':nivel,'mensagem':msg,'ts':ts})\n    print(f'[{ts}] {nivel}: {msg}')\ndef relatorio_logs():\n    niveis=Counter(l['nivel'] for l in LOGS)\n    erros=[l for l in LOGS if l['nivel']=='ERROR'][-3:]\n    return {'total_por_nivel':dict(niveis),'ultimos_erros':erros}"},
    {"order":3,"difficulty":"medio","xp_reward":25,
     "title":"Exportador CSV + Relatório JSON",
     "description":"Dada a lista de vendedores, exporte para CSV, leia e calcule total. Depois salve o relatório em JSON.\n\n```python\nvendedores = [{'nome':'Carlos','vendas':45,'comissao':2250.0},{'nome':'Maria','vendas':72,'comissao':3600.0}]\n```",
     "hint":"DictWriter para escrever, DictReader para ler. Valores do CSV sempre são string — converta com float().",
     "starter_code":"import csv, json\n\nvendedores = [\n    {'nome':'Carlos','vendas':45,'comissao':2250.0},\n    {'nome':'Maria','vendas':72,'comissao':3600.0},\n]\n\ndef exportar_csv(dados, arquivo): pass\ndef calcular_relatorio(arquivo): pass\n\nexportar_csv(vendedores, 'vendedores.csv')\nprint(calcular_relatorio('vendedores.csv'))\n",
     "solution_hint":"def exportar_csv(dados,arq):\n    with open(arq,'w',newline='',encoding='utf-8') as f:\n        w=csv.DictWriter(f,fieldnames=dados[0].keys())\n        w.writeheader(); w.writerows(dados)\ndef calcular_relatorio(arq):\n    with open(arq,'r',encoding='utf-8') as f:\n        rows=list(csv.DictReader(f))\n        total=sum(float(r['comissao']) for r in rows)\n        return {'vendedores':len(rows),'total_comissoes':total}"},
    {"order":4,"difficulty":"medio","xp_reward":25,
     "title":"Banco de Dados em JSON",
     "description":"Crie CRUD completo persistido em arquivo JSON:\n- criar_registro(dados) → dict com id automático\n- buscar_por_id(id) → dict ou None\n- atualizar_registro(id, novos_dados) → bool\n- deletar_registro(id) → bool",
     "hint":"Sempre carregue, modifique em memória e salve de volta. IDs: max(r['id'] for r in db, default=0) + 1",
     "starter_code":"import json, os\nARQ = 'banco.json'\n\ndef salvar_db(dados): pass\ndef carregar_db(): pass\ndef criar_registro(dados): pass\ndef buscar_por_id(id): pass\n\nr1 = criar_registro({'nome':'Produto A','preco':99.90})\nprint(buscar_por_id(1))\n",
     "solution_hint":"def salvar_db(d):\n    with open(ARQ,'w',encoding='utf-8') as f: json.dump(d,f,ensure_ascii=False,indent=2)\ndef carregar_db():\n    if not os.path.exists(ARQ): return []\n    with open(ARQ,'r',encoding='utf-8') as f: return json.load(f)\ndef criar_registro(d):\n    db=carregar_db(); nid=max((r['id'] for r in db),default=0)+1\n    r={'id':nid,**d}; db.append(r); salvar_db(db); return r\ndef buscar_por_id(id): return next((r for r in carregar_db() if r['id']==id),None)"},
    {"order":5,"difficulty":"dificil","xp_reward":35,
     "title":"Pipeline de Importação",
     "description":"Crie pipeline que: leia CSV com data/produto/quantidade/preco, valide cada linha, calcule totais, agrupe por produto e exporte relatório JSON com válidas/inválidas/resumo.",
     "hint":"Crie validar_linha() separada. datetime.strptime() para datas. Inclua número da linha nos erros.",
     "starter_code":"import csv, json\nfrom datetime import datetime\nfrom collections import defaultdict\n\nCSV = \"\"\"data,produto,quantidade,preco_unitario\n2025-01-15,Notebook,2,2500.00\n2025-01-15,Mouse,,80.00\n2025-01-16,Teclado,1,150.00\n\"\"\"\nwith open('vendas.csv','w') as f: f.write(CSV)\n\ndef importar_vendas(arquivo): pass\n\nprint(json.dumps(importar_vendas('vendas.csv'), ensure_ascii=False, indent=2))\n",
     "solution_hint":"def importar_vendas(arq):\n    validas,invalidas,por_prod=[],[],defaultdict(float)\n    with open(arq,'r',encoding='utf-8') as f:\n        for i,row in enumerate(csv.DictReader(f),1):\n            erros=[]\n            if not row.get('quantidade'): erros.append('qtd vazia')\n            try: q=int(row.get('quantidade',0)); assert q>0\n            except: erros.append('qtd inválida')\n            try: p=float(row.get('preco_unitario',0)); assert p>0\n            except: erros.append('preço inválido')\n            try: datetime.strptime(row.get('data',''),'%Y-%m-%d')\n            except: erros.append('data inválida')\n            if erros: invalidas.append({'linha':i,'erros':erros})\n            else:\n                total=int(row['quantidade'])*float(row['preco_unitario'])\n                validas.append({**row,'total':total}); por_prod[row['produto']]+=total\n    return {'validas':len(validas),'invalidas':invalidas,'por_produto':dict(por_prod)}"},
   ],
  },
  {
   "order":5,"icon":"🏗️","color":"#ef4444","xp_reward":130,
   "title":"Orientação a Objetos",
   "description":"Classes, objetos, herança e polimorfismo com exemplos reais. A base para qualquer framework Python.",
   "lessons":[
    {"order":1,"title":"Classes e Objetos","reading_minutes":10,
     "content":"Uma classe é um modelo. Um objeto é uma instância. Use @property para controlar acesso a atributos sensíveis.",
     "code_example":"class ContaBancaria:\n    def __init__(self, titular: str, saldo: float = 0):\n        self.titular = titular\n        self._saldo = saldo\n        self._historico = []\n    \n    def depositar(self, valor: float):\n        if valor <= 0: raise ValueError('Valor deve ser positivo')\n        self._saldo += valor\n        self._historico.append(f'+R$ {valor:.2f}')\n    \n    def sacar(self, valor: float) -> bool:\n        if valor > self._saldo: return False\n        self._saldo -= valor\n        self._historico.append(f'-R$ {valor:.2f}')\n        return True\n    \n    @property\n    def saldo(self): return self._saldo\n    \n    def __repr__(self):\n        return f'Conta({self.titular}, R${self._saldo:.2f})'\n\nconta = ContaBancaria('Ana', 1000)\nconta.depositar(500)\nconta.sacar(200)\nprint(conta)  # Conta(Ana, R$1300.00)",
     "real_world_case":"Todo ORM usa classes para tabelas. Todo framework usa classes para views. OOP é pré-requisito para qualquer framework Python sério.",
     "best_practice":"Use @property para controlar acesso. Implemente __repr__ para facilitar debug. Prefira composição à herança."},
    {"order":2,"title":"Herança e Polimorfismo","reading_minutes":9,
     "content":"Herança permite que uma classe herde de outra. Polimorfismo: objetos diferentes respondem ao mesmo método de formas diferentes. ABC define interfaces.",
     "code_example":"from abc import ABC, abstractmethod\n\nclass Pagamento(ABC):\n    def __init__(self, valor: float):\n        self.valor = valor\n    \n    @abstractmethod\n    def processar(self) -> dict:\n        pass\n\nclass PagamentoPix(Pagamento):\n    def __init__(self, valor, chave):\n        super().__init__(valor)\n        self.chave = chave\n    \n    def processar(self):\n        return {'metodo':'pix','valor':self.valor,'status':'aprovado'}\n\nclass PagamentoCartao(Pagamento):\n    def processar(self):\n        return {'metodo':'cartao','valor':self.valor,'parcelas':1}\n\n# Polimorfismo\npagamentos = [PagamentoPix(150.0,'ana@pix'), PagamentoCartao(300.0)]\nfor pag in pagamentos:\n    print(pag.processar())  # cada um executa diferente",
     "real_world_case":"Sistemas de pagamento: classe base Pagamento com Pix, Cartao, Boleto. Código que chama processar() é o mesmo para todos.",
     "best_practice":"Use ABC para definir interfaces. Sempre chame super().__init__(). Herança = 'é um', composição = 'tem um'."},
   ],
   "exercises":[
    {"order":1,"difficulty":"facil","xp_reward":20,
     "title":"Produto com Property",
     "description":"Crie Produto(nome, preco, quantidade):\n- @property preco com setter que valida > 0\n- @property em_estoque (bool)\n- vender(qtd) levanta ValueError se insuficiente\n- repor(qtd)\n- __repr__",
     "hint":"No setter: if v <= 0: raise ValueError(...). @property retorna self._preco.",
     "starter_code":"class Produto:\n    def __init__(self, nome, preco, quantidade=0):\n        self.nome = nome\n        self.preco = preco   # chama o setter\n        self._quantidade = quantidade\n    # implemente property, vender, repor, __repr__\n\np = Produto('Notebook', 2500.0, 10)\np.vender(3)\nprint(p)\n",
     "solution_hint":"@property\ndef preco(self): return self._preco\n@preco.setter\ndef preco(self,v):\n    if v<=0: raise ValueError('Preço deve ser positivo')\n    self._preco=v\n@property\ndef em_estoque(self): return self._quantidade>0\ndef vender(self,q):\n    if q>self._quantidade: raise ValueError('Estoque insuficiente')\n    self._quantidade-=q\ndef __repr__(self): return f'Produto({self.nome}, R${self._preco:.2f})'"},
    {"order":2,"difficulty":"facil","xp_reward":20,
     "title":"Hierarquia de Funcionários",
     "description":"Crie:\n- Funcionario(nome, salario_base) com calcular_salario() e __str__\n- Desenvolvedor(nivel) — 'junior'(+0%), 'pleno'(+30%), 'senior'(+60%)\n- Gerente(n_subordinados) — bônus: n_subordinados × 500",
     "hint":"super().__init__(nome, salario_base). Use dict para bônus de nível.",
     "starter_code":"class Funcionario:\n    def __init__(self, nome, salario_base): self.nome=nome; self.salario_base=salario_base\n    def calcular_salario(self): return self.salario_base\n    def __str__(self): return f'{self.nome}: R$ {self.calcular_salario():.2f}'\n\nclass Desenvolvedor(Funcionario): pass\nclass Gerente(Funcionario): pass\n\nfor f in [Desenvolvedor('Ana',5000,'junior'),Desenvolvedor('Bob',5000,'senior'),Gerente('Carlos',8000,5)]:\n    print(f)\n",
     "solution_hint":"class Desenvolvedor(Funcionario):\n    BONUS={'junior':0,'pleno':.3,'senior':.6}\n    def __init__(self,n,s,niv): super().__init__(n,s); self.nivel=niv\n    def calcular_salario(self): return self.salario_base*(1+self.BONUS.get(self.nivel,0))\nclass Gerente(Funcionario):\n    def __init__(self,n,s,sub): super().__init__(n,s); self.subs=sub\n    def calcular_salario(self): return self.salario_base+self.subs*500"},
    {"order":3,"difficulty":"medio","xp_reward":25,
     "title":"Sistema de Notificações",
     "description":"Implemente:\n- Notificacao(ABC) com enviar() abstrato\n- Email(dest, msg, assunto).enviar()\n- SMS(dest, msg).enviar() — falha se msg > 160 chars\n- NotificacaoMulticanal([notificacoes]).enviar() — tenta até ter sucesso",
     "hint":"NotificacaoMulticanal usa composição. enviar() retorna True no primeiro sucesso.",
     "starter_code":"from abc import ABC, abstractmethod\n\nclass Notificacao(ABC):\n    def __init__(self,dest,msg): self.dest=dest; self.msg=msg\n    @abstractmethod\n    def enviar(self) -> bool: pass\n\nclass Email(Notificacao):\n    def __init__(self,dest,msg,assunto=''): super().__init__(dest,msg); self.assunto=assunto\n    def enviar(self): print(f'[EMAIL] {self.assunto} → {self.dest}'); return True\n\nclass SMS(Notificacao):\n    def enviar(self):\n        if len(self.msg)>160: print('[SMS] Mensagem longa'); return False\n        print(f'[SMS] {self.dest}: {self.msg[:50]}'); return True\n\nclass NotificacaoMulticanal:\n    pass  # implemente\n\nn = NotificacaoMulticanal([SMS('11999','msg curta'), Email('a@b.com','msg','Assunto')])\nprint(n.enviar())\n",
     "solution_hint":"class NotificacaoMulticanal:\n    def __init__(self,notifs): self.notifs=notifs\n    def enviar(self):\n        for n in self.notifs:\n            if n.enviar(): return True\n        return False"},
    {"order":4,"difficulty":"medio","xp_reward":25,
     "title":"Carrinho de Compras OOP",
     "description":"Implemente:\n- Produto(codigo, nome, preco)\n- ItemCarrinho(produto, quantidade) com @property subtotal\n- Carrinho com: adicionar(produto, qtd), @property total, aplicar_desconto(pct), finalizar() → dict",
     "hint":"Carrinho guarda lista de ItemCarrinho. finalizar() retorna {itens, bruto, desconto_pct, total}.",
     "starter_code":"class Produto:\n    def __init__(self,cod,nome,preco): self.cod=cod; self.nome=nome; self.preco=preco\n\nclass ItemCarrinho:\n    def __init__(self,produto,qtd): self.produto=produto; self.qtd=qtd\n    @property\n    def subtotal(self): pass\n\nclass Carrinho:\n    def __init__(self): self._itens=[]; self._desc=0\n    def adicionar(self,prod,qtd=1): pass\n    @property\n    def total(self): pass\n    def aplicar_desconto(self,pct): pass\n    def finalizar(self): pass\n\nc=Carrinho()\nc.adicionar(Produto('P1','Notebook',2500),1)\nc.adicionar(Produto('P2','Mouse',80),2)\nc.aplicar_desconto(10)\nprint(c.finalizar())\n",
     "solution_hint":"@property\ndef subtotal(self): return self.produto.preco*self.qtd\nclass Carrinho:\n    def adicionar(self,p,q=1):\n        ex=next((i for i in self._itens if i.produto.cod==p.cod),None)\n        if ex: ex.qtd+=q\n        else: self._itens.append(ItemCarrinho(p,q))\n    @property\n    def total(self): return sum(i.subtotal for i in self._itens)*(1-self._desc/100)\n    def aplicar_desconto(self,p): self._desc=p\n    def finalizar(self): b=sum(i.subtotal for i in self._itens); return {'itens':len(self._itens),'bruto':b,'desconto_pct':self._desc,'total':self.total}"},
    {"order":5,"difficulty":"dificil","xp_reward":40,
     "title":"Mini ORM em Memória",
     "description":"Simule como SQLAlchemy funciona:\n- Model base: save(), delete(), to_dict(), all(), filter(**kwargs), get(id)\n- Usuario(Model) com nome, email, ativo=True\n- IDs automáticos\n- filter() compara atributos com **kwargs",
     "hint":"Use variável de classe _registros = {} e _next_id = 1.",
     "starter_code":"class Model:\n    _registros = {}; _next_id = 1\n    def save(self): pass\n    def delete(self): pass\n    @classmethod\n    def all(cls): pass\n    @classmethod\n    def filter(cls, **kwargs): pass\n    @classmethod\n    def get(cls, id): pass\n\nclass Usuario(Model):\n    def __init__(self,nome,email,ativo=True): self.id=None; self.nome=nome; self.email=email; self.ativo=ativo\n    def __repr__(self): return f'Usuario({self.nome})'\n\nu1=Usuario('Ana','ana@mail.com'); u1.save()\nu2=Usuario('Bob','bob@mail.com',ativo=False); u2.save()\nprint(Usuario.all())\nprint(Usuario.filter(ativo=True))\n",
     "solution_hint":"class Model:\n    _registros={}; _next_id=1\n    def save(self):\n        cls=type(self)\n        if not self.id: self.id=cls._next_id; cls._next_id+=1\n        cls._registros[self.id]=self\n    def delete(self): type(self)._registros.pop(self.id,None)\n    @classmethod\n    def all(cls): return list(cls._registros.values())\n    @classmethod\n    def filter(cls,**kw): return [o for o in cls._registros.values() if all(getattr(o,k,None)==v for k,v in kw.items())]\n    @classmethod\n    def get(cls,id): return cls._registros.get(id)"},
   ],
  },
  {
   "order":6,"icon":"🔬","color":"#f59e0b","xp_reward":140,
   "title":"Projeto Básico: Sistema de Cadastro",
   "description":"Aplique tudo do nível básico num sistema real de cadastro com persistência em JSON e interface de linha de comando.",
   "lessons":[
    {"order":1,"title":"Projeto Completo: Do Planejamento ao Código","reading_minutes":10,
     "content":"Um projeto real não nasce pronto. Você planeja, define entidades, implementa e testa. Este módulo guia pela construção de um sistema completo.",
     "code_example":"# Sistema de Cadastro de Clientes\n# Entidades: Cliente (dataclass)\n# Operações: CRUD + relatórios\n# Persistência: arquivo JSON\n# Validações: email, CPF, campos obrigatórios\n\nfrom dataclasses import dataclass, asdict, field\nfrom datetime import datetime\nfrom typing import Optional\nimport json, os, re\n\n@dataclass\nclass Cliente:\n    nome: str\n    email: str\n    cpf: str\n    id: int = 0\n    ativo: bool = True\n    criado_em: str = field(default_factory=lambda: datetime.now().isoformat())\n    \n    def __post_init__(self):\n        self.email = self.email.lower().strip()\n        self.cpf = re.sub(r'\\D', '', self.cpf)\n        if '@' not in self.email:\n            raise ValueError(f'Email inválido: {self.email}')\n        if len(self.cpf) != 11:\n            raise ValueError(f'CPF deve ter 11 dígitos')",
     "real_world_case":"Todo sistema empresarial tem cadastros — clientes, fornecedores, funcionários. CRUD com validações é a base do backend.",
     "best_practice":"Valide dados na criação (__post_init__). Mantenha lógica de persistência separada da lógica de negócio."},
   ],
   "exercises":[
    {"order":1,"difficulty":"medio","xp_reward":35,
     "title":"CRUD de Clientes",
     "description":"Sistema completo com dataclass + JSON:\n- Cliente(nome, email, cpf, id, ativo)\n- criar_cliente() com validação\n- buscar_cliente(id)\n- atualizar_cliente(id, **campos)\n- desativar_cliente(id) (soft delete)\n- listar_clientes(apenas_ativos=True)",
     "hint":"Use asdict() para serializar. Para desserializar: Cliente(**dict). Valide email com 'if '@' not in email'.",
     "starter_code":"import json, os, re\nfrom dataclasses import dataclass, asdict, field\nfrom datetime import datetime\n\n@dataclass\nclass Cliente:\n    nome: str; email: str; cpf: str\n    id: int = 0; ativo: bool = True\n    criado_em: str = field(default_factory=lambda: datetime.now().isoformat())\n\nARQ = 'clientes.json'\n\ndef criar_cliente(nome, email, cpf): pass\ndef buscar_cliente(id): pass\ndef listar_clientes(apenas_ativos=True): pass\n\ncriar_cliente('Ana Silva', 'ana@mail.com', '12345678901')\nprint(listar_clientes())\n",
     "solution_hint":"def _carregar():\n    if not os.path.exists(ARQ): return []\n    with open(ARQ,'r',encoding='utf-8') as f: return json.load(f)\ndef _salvar(d):\n    with open(ARQ,'w',encoding='utf-8') as f: json.dump(d,f,ensure_ascii=False,indent=2)\ndef criar_cliente(n,e,c):\n    if '@' not in e: raise ValueError('Email inválido')\n    db=_carregar(); nid=max((x['id'] for x in db),default=0)+1\n    cli={'id':nid,'nome':n,'email':e.lower(),'cpf':re.sub(r'\\D','',c),'ativo':True,'criado_em':datetime.now().isoformat()}\n    db.append(cli); _salvar(db); return cli\ndef listar_clientes(sa=True): return [x for x in _carregar() if not sa or x['ativo']]"},
    {"order":2,"difficulty":"medio","xp_reward":35,
     "title":"Relatórios e Estatísticas",
     "description":"Adicione ao sistema:\n- relatorio_geral() → {total, ativos, inativos, cadastrados_esta_semana}\n- exportar_relatorio(arquivo='relatorio.txt') → salva formatado",
     "hint":"Para esta_semana: compare datetime.fromisoformat() com datetime.now() - timedelta(days=7).",
     "starter_code":"from datetime import datetime, timedelta\n\ndef relatorio_geral(clientes: list) -> dict:\n    pass\n\ndef exportar_relatorio(clientes: list, arquivo='relatorio.txt'):\n    pass\n\nclientes_teste = [\n    {'nome':'Ana','email':'ana@mail.com','ativo':True,'criado_em':datetime.now().isoformat()},\n    {'nome':'Bob','email':'bob@mail.com','ativo':False,'criado_em':'2024-01-01T10:00:00'},\n]\nprint(relatorio_geral(clientes_teste))\n",
     "solution_hint":"def relatorio_geral(cls):\n    semana=datetime.now()-timedelta(days=7)\n    recentes=sum(1 for c in cls if datetime.fromisoformat(c['criado_em'])>semana)\n    return {'total':len(cls),'ativos':sum(1 for c in cls if c['ativo']),'inativos':sum(1 for c in cls if not c['ativo']),'semana':recentes}\ndef exportar_relatorio(cls,arq='relatorio.txt'):\n    with open(arq,'w',encoding='utf-8') as f:\n        f.write(f'=== RELATÓRIO ===\\nGerado: {datetime.now().strftime(\"%d/%m/%Y %H:%M\")}\\n\\n')\n        for c in cls: f.write(f'- {c[\"nome\"]} ({c[\"email\"]}) — {\"Ativo\" if c[\"ativo\"] else \"Inativo\"}\\n')"},
    {"order":3,"difficulty":"medio","xp_reward":35,
     "title":"CLI Interativo",
     "description":"Crie menu de linha de comando:\n```\n1. Novo cliente\n2. Buscar\n3. Listar\n4. Relatório\n5. Sair\n```\nUse while True, trate erros em cada opção sem deixar o programa travar.",
     "hint":"Use dict de opções. Envolva cada operação em try/except dentro do loop.",
     "starter_code":"def menu():\n    while True:\n        print('\\n1. Novo cliente')\n        print('2. Listar todos')\n        print('3. Sair')\n        escolha = input('Opção: ').strip()\n        if escolha == '3': print('Até logo!'); break\n        elif escolha == '1':\n            pass  # implemente\n        elif escolha == '2':\n            pass  # implemente\n\n# menu()  # descomente para testar\n",
     "solution_hint":"if escolha=='1':\n    try:\n        n=input('Nome: '); e=input('Email: '); c=input('CPF: ')\n        criar_cliente(n,e,c); print('Criado!')\n    except Exception as ex: print(f'Erro: {ex}')\nelif escolha=='2':\n    cls=listar_clientes()\n    for c in cls: print(f'#{c[\"id\"]} {c[\"nome\"]} — {c[\"email\"]}')"},
    {"order":4,"difficulty":"dificil","xp_reward":50,
     "title":"Sistema OOP Completo",
     "description":"Refatore usando OOP:\n- GerenciadorClientes(persistencia): adicionar, buscar, listar, relatorio\n- Validador (@staticmethod): validar_email, validar_cpf\n- PersistenciaJSON: salvar, carregar, fazer_backup\n\nAs 3 classes trabalham juntas mas são independentes.",
     "hint":"GerenciadorClientes recebe PersistenciaJSON no __init__. Validador só tem métodos estáticos (@staticmethod).",
     "starter_code":"class Validador:\n    @staticmethod\n    def validar_email(email): pass\n    @staticmethod\n    def validar_cpf(cpf): pass\n\nclass PersistenciaJSON:\n    def __init__(self, arquivo): self.arquivo = arquivo\n    def salvar(self, dados): pass\n    def carregar(self): pass\n\nclass GerenciadorClientes:\n    def __init__(self, persistencia):\n        self.db = persistencia\n        self._clientes = self.db.carregar()\n    def adicionar(self, nome, email, cpf): pass\n    def listar(self, apenas_ativos=True): pass\n\npersist = PersistenciaJSON('clientes_v2.json')\ngc = GerenciadorClientes(persist)\ngc.adicionar('Ana', 'ana@mail.com', '12345678901')\nprint(gc.listar())\n",
     "solution_hint":"class Validador:\n    @staticmethod\n    def validar_email(e): return '@' in e and '.' in e.split('@')[-1]\n    @staticmethod\n    def validar_cpf(c): import re; return len(re.sub(r'\\D','',c))==11\nclass PersistenciaJSON:\n    def carregar(self):\n        import json,os; \n        if not os.path.exists(self.arquivo): return []\n        with open(self.arquivo,'r',encoding='utf-8') as f: return json.load(f)\n    def salvar(self,d):\n        import json\n        with open(self.arquivo,'w',encoding='utf-8') as f: json.dump(d,f,ensure_ascii=False,indent=2)"},
    {"order":5,"difficulty":"dificil","xp_reward":50,
     "title":"Importador em Lote",
     "description":"Crie importador que leia CSV de clientes, valide cada linha, cadastre os válidos e gere relatório:\n- Total processado, importados, rejeitados com motivo\n- Tempo de execução\n- Relatório salvo em JSON",
     "hint":"time.time() antes e depois. Função processar_linha() retorna (bool, motivo). Colete resultados em lista.",
     "starter_code":"import csv, json, time, re\nfrom io import StringIO\n\nCSV_SIMULADO = \"\"\"nome,email,cpf\nAna Silva,ana@mail.com,12345678901\nBob Santos,email_invalido,98765432100\nCarlos,carlos@mail.com,123\nDiana,diana@mail.com,11122233344\n\"\"\"\n\ndef importar_clientes(csv_texto: str) -> dict:\n    inicio = time.time()\n    # processe cada linha\n    pass\n\nresult = importar_clientes(CSV_SIMULADO)\nprint(json.dumps(result, ensure_ascii=False, indent=2))\n",
     "solution_hint":"def importar_clientes(txt):\n    inicio=time.time(); ok,falhas=[],[]\n    for i,row in enumerate(csv.DictReader(StringIO(txt)),1):\n        erros=[]\n        if not row.get('nome'): erros.append('nome vazio')\n        if '@' not in row.get('email',''): erros.append('email inválido')\n        if len(re.sub(r'\\D','',row.get('cpf','')))<>11: erros.append('CPF inválido')\n        if erros: falhas.append({'linha':i,'erros':erros})\n        else: ok.append(dict(row))\n    return {'total':len(ok)+len(falhas),'importados':len(ok),'rejeitados':len(falhas),'falhas':falhas,'tempo':round(time.time()-inicio,3)}"},
   ],
  },
]

# Módulos intermediários e avançados — estrutura resumida para seed
INTERMEDIARIO_MODULES = [
  {"order":1,"icon":"🌐","color":"#3b82f6","xp_reward":150,"title":"HTTP e APIs REST com FastAPI","description":"HTTP, consumir APIs externas com httpx e criar APIs profissionais com FastAPI e Pydantic.","lessons":[],"exercises":[]},
  {"order":2,"icon":"🗄️","color":"#10b981","xp_reward":160,"title":"Banco de Dados com SQLAlchemy","description":"Models ORM, relacionamentos, CRUD, queries avançadas, transactions e migrations.","lessons":[],"exercises":[]},
  {"order":3,"icon":"🔑","color":"#8b5cf6","xp_reward":170,"title":"Autenticação JWT e Segurança","description":"Hash com bcrypt, tokens JWT, refresh tokens, RBAC e proteção de endpoints.","lessons":[],"exercises":[]},
  {"order":4,"icon":"⚡","color":"#f59e0b","xp_reward":180,"title":"Async, Testes e Deploy","description":"Programação assíncrona, pytest com mocks, Docker e variáveis de ambiente.","lessons":[],"exercises":[]},
  {"order":5,"icon":"🔧","color":"#06b6d4","xp_reward":190,"title":"Projeto Integrador Intermediário","description":"API completa de gerenciamento de projetos com equipes, tarefas e relatórios.","lessons":[],"exercises":[]},
  {"order":6,"icon":"📐","color":"#ef4444","xp_reward":200,"title":"Boas Práticas e Padrões","description":"Clean Code, SOLID simplificado, logging profissional e configurações por ambiente.","lessons":[],"exercises":[]},
]

AVANCADO_MODULES = [
  {"order":1,"icon":"🚀","color":"#3b82f6","xp_reward":250,"title":"Performance e Otimização","description":"Profiling, cache avançado, otimização de queries N+1, rate limiting e background jobs.","lessons":[],"exercises":[]},
  {"order":2,"icon":"🏛️","color":"#8b5cf6","xp_reward":260,"title":"Arquitetura e Padrões de Design","description":"Clean Architecture, Repository Pattern, Service Layer, CQRS e Event-Driven Architecture.","lessons":[],"exercises":[]},
  {"order":3,"icon":"🔬","color":"#10b981","xp_reward":270,"title":"Testes Avançados e Qualidade","description":"TDD, Property-Based Testing, mutation testing e pipeline de qualidade completo.","lessons":[],"exercises":[]},
  {"order":4,"icon":"☁️","color":"#f59e0b","xp_reward":280,"title":"Cloud e Escalabilidade","description":"PostgreSQL em produção, Redis, monitoramento com métricas e estratégias de escalabilidade.","lessons":[],"exercises":[]},
  {"order":5,"icon":"🎓","color":"#ef4444","xp_reward":300,"title":"Projeto Final Avançado","description":"Sistema de pagamentos com Clean Architecture, testes, métricas e deploy em produção.","lessons":[],"exercises":[]},
]
