"""Currículo — Nível Básico, módulos 1-3."""

BASICO_M1_3 = [
  {
   "order":1,"icon":"🐣","color":"#3b82f6","xp_reward":80,
   "title":"Seu Primeiro Python",
   "description":"Entenda o que é Python, por que ele domina o mercado e escreva suas primeiras linhas. Sem jargão, sem pressa.",
   "lessons":[
    {"order":1,"title":"O que é Python e por que aprender?","reading_minutes":6,
     "content":"Python é a linguagem mais usada do mundo — presente no Instagram, Netflix, Google e Nubank.\n\nPor que Python para backend?\n• Sintaxe próxima do português — você lê o código quase como uma frase\n• Mercado de trabalho enorme e salários altos\n• Uma biblioteca para tudo: banco, APIs, IA, automação\n• Comunidade gigante — qualquer dúvida tem resposta",
     "code_example":"# Seu primeiro programa\nprint('Olá, mundo!')\n\n# Python é legível\nnome = 'Ana'\nidade = 25\nprint(f'Meu nome é {nome} e tenho {idade} anos')\n\n# Compare com Java que faz o mesmo:\n# public class Main {\n#   public static void main(String[] args) {\n#     System.out.println(\"Olá\");\n#   }\n# }\n# Python é muito mais simples!",
     "real_world_case":"O Nubank usa Python para processar milhões de transações por dia. O Instagram foi construído em Python. A NASA analisa dados de missões com Python.",
     "best_practice":"Escreva comentários que explicam o PORQUÊ, não o QUÊ. Use nomes descritivos: 'preco_produto' é melhor que 'p'."},
    {"order":2,"title":"Variáveis e Tipos de Dados","reading_minutes":8,
     "content":"Variáveis são caixas onde você guarda informações. Python descobre o tipo automaticamente.\n\nTipos principais:\n• str (texto): 'Ana', \"Python\"\n• int (inteiro): 25, -3, 1000\n• float (decimal): 9.99, 3.14\n• bool (verdadeiro/falso): True, False\n• None (ausência de valor)",
     "code_example":"nome = 'Maria Silva'\nidade = 28\nsaldo = 1250.50\nativo = True\ntelefone = None  # ainda não temos\n\n# Verificando o tipo\nprint(type(nome))    # <class 'str'>\nprint(type(idade))   # <class 'int'>\n\n# Conversão entre tipos\nidade_texto = str(idade)       # '28'\nvalor = float('299.90')        # 299.90\n\n# Caso real: dados de formulário chegam como texto\ndado = '299.90'\npreco = float(dado)\nprint(f'Com desconto: R$ {preco * 0.9:.2f}')",
     "real_world_case":"Em e-commerce, preços vêm do banco como Decimal, quantidades como int, nomes como str. Misturar tipos sem conversão causa bugs que derrubam sistemas.",
     "best_practice":"Use snake_case (underline): 'preco_produto'. Evite abreviações obscuras. Seja consistente."},
    {"order":3,"title":"f-strings e Formatação","reading_minutes":5,
     "content":"f-strings são a forma moderna de formatar texto em Python. Mais legíveis e rápidas que concatenação.",
     "code_example":"nome = 'Ana'\npreco = 1234.5\npct = 0.856\n\n# f-string — USE SEMPRE ESTA forma\nmsg = f'Olá, {nome}! Preço: R$ {preco:.2f}'\n\n# Formatações úteis\nprint(f'R$ {preco:,.2f}')      # R$ 1,234.50\nprint(f'{pct:.1%}')            # 85.6%\nprint(f'{42:05d}')             # 00042\n\n# Multi-linha\nrecibo = f\"\"\"\n=== RECIBO ===\nCliente: {nome}\nTotal:   R$ {preco:.2f}\n\"\"\"\nprint(recibo)",
     "real_world_case":"Relatórios, notas fiscais, confirmações de pedido — tudo usa formatação.",
     "best_practice":"Sempre use f-strings (Python 3.6+). Para dinheiro: {valor:.2f}."},
   ],
   "exercises":[
    {"order":1,"difficulty":"facil","xp_reward":15,
     "title":"Olá, Programador!",
     "description":"Crie um programa que peça o nome e a cidade do usuário e imprima uma saudação personalizada.\n\nExemplo de saída:\n```\nBem-vindo(a), Carlos de São Paulo!\nPython é incrível, Carlos!\n```",
     "hint":"Use input() para receber os dados e f-string para montar a mensagem.",
     "starter_code":"nome = input('Seu nome: ')\n# adicione input para cidade\n# imprima as duas linhas de saudação\n",
     "solution_hint":"nome = input('Seu nome: ')\ncidade = input('Sua cidade: ')\nprint(f'Bem-vindo(a), {nome} de {cidade}!')\nprint(f'Python é incrível, {nome}!')"},
    {"order":2,"difficulty":"facil","xp_reward":15,
     "title":"Calculadora de Desconto",
     "description":"Receba o preço de um produto e um percentual de desconto. Mostre:\n- O valor do desconto\n- O preço final\n\nExemplo:\n```\nProduto: R$ 200.00\nDesconto (10%): R$ 20.00\nVocê paga: R$ 180.00\n```",
     "hint":"Converta inputs para float. Desconto = preco * (pct / 100). Use :.2f para dinheiro.",
     "starter_code":"preco = float(input('Preço: R$ '))\ndesconto_pct = float(input('Desconto (%): '))\n# calcule e imprima\n",
     "solution_hint":"desconto = preco * (desconto_pct / 100)\nfinal = preco - desconto\nprint(f'Produto: R$ {preco:.2f}')\nprint(f'Desconto ({desconto_pct:.0f}%): R$ {desconto:.2f}')\nprint(f'Você paga: R$ {final:.2f}')"},
    {"order":3,"difficulty":"facil","xp_reward":15,
     "title":"Conversor de Temperatura",
     "description":"Receba uma temperatura em Celsius e mostre em Fahrenheit e Kelvin.\n\nFórmulas:\n- F = (C × 9/5) + 32\n- K = C + 273.15",
     "hint":"Use float() para o input. Formate com 1 casa decimal.",
     "starter_code":"celsius = float(input('Temperatura em Celsius: '))\n# calcule e mostre os 3 valores\n",
     "solution_hint":"fahrenheit = (celsius * 9/5) + 32\nkelvin = celsius + 273.15\nprint(f'{celsius:.1f}°C = {fahrenheit:.1f}°F = {kelvin:.1f}K')"},
    {"order":4,"difficulty":"medio","xp_reward":25,
     "title":"Ficha de Cadastro",
     "description":"Solicite: nome, email, ano de nascimento e salário. Calcule a idade e mostre uma ficha formatada com todos os dados, incluindo salário como moeda.",
     "hint":"Use datetime.datetime.now().year para o ano atual.",
     "starter_code":"import datetime\nANO_ATUAL = datetime.datetime.now().year\n\n# Colete os dados, calcule a idade e mostre a ficha\n",
     "solution_hint":"nome = input('Nome: ')\nemail = input('Email: ')\nano = int(input('Ano de nascimento: '))\nsal = float(input('Salário: R$ '))\nidade = ANO_ATUAL - ano\nprint(f'\\n=== FICHA ===')\nprint(f'Nome: {nome} | Idade: {idade} anos')\nprint(f'Email: {email}')\nprint(f'Salário: R$ {sal:,.2f}')"},
    {"order":5,"difficulty":"medio","xp_reward":25,
     "title":"Analisador de Tipos",
     "description":"Crie analisar(valor) que retorne um dicionário com:\n- tipo: nome do tipo Python\n- e_numero: True se int ou float\n- e_texto: True se str\n- e_vazio: True se None, '' ou 0\n- descricao: texto amigável\n\nTeste com: 42, 'Python', 3.14, None, True",
     "hint":"Use isinstance(valor, int). Para None use 'valor is None'.",
     "starter_code":"def analisar(valor):\n    pass\n\nprint(analisar(42))\nprint(analisar('Python'))\nprint(analisar(None))\n",
     "solution_hint":"def analisar(v):\n    t=type(v).__name__\n    e_num=isinstance(v,(int,float)) and not isinstance(v,bool)\n    e_txt=isinstance(v,str)\n    e_vaz=v is None or v=='' or v==0\n    if isinstance(v,bool): desc=f'Booleano: {v}'\n    elif e_num: desc=f'Número {t}: {v}'\n    elif e_txt: desc=f'Texto: \"{v}\" ({len(v)} chars)'\n    elif v is None: desc='Valor nulo'\n    else: desc=f'Outro: {v}'\n    return {'tipo':t,'e_numero':e_num,'e_texto':e_txt,'e_vazio':e_vaz,'descricao':desc}"},
   ],
  },
  {
   "order":2,"icon":"🔀","color":"#8b5cf6","xp_reward":90,
   "title":"Decisões e Repetições",
   "description":"if/elif/else para decisões, for e while para repetições. Esses dois conceitos resolvem 70% dos problemas reais.",
   "lessons":[
    {"order":1,"title":"Condicionais: if, elif, else","reading_minutes":8,
     "content":"Condicionais permitem ao programa tomar decisões.\n\nOperadores de comparação: ==, !=, >, <, >=, <=\nOperadores lógicos: and, or, not",
     "code_example":"nota = float(input('Nota: '))\n\nif nota >= 9:\n    conceito = 'A — Excelente!'\nelif nota >= 7:\n    conceito = 'B — Bom!'\nelif nota >= 5:\n    conceito = 'C — Aprovado'\nelse:\n    conceito = 'D — Reprovado'\n\nprint(f'Conceito: {conceito}')\n\n# Combinando condições\nidade = 20\ntem_renda = True\n\nif idade >= 18 and tem_renda:\n    print('Pode abrir conta')\n\n# Ternário — para casos simples\nstatus = 'ativo' if tem_renda else 'inativo'",
     "real_world_case":"Todo sistema de login usa condicionais. Todo cálculo de frete, desconto e aprovação de crédito usa ifs.",
     "best_practice":"Evite ifs aninhados demais. Use 'if ativo:' em vez de 'if ativo == True:'."},
    {"order":2,"title":"Loops: for e while","reading_minutes":9,
     "content":"for repete para cada item de uma sequência. while repete enquanto uma condição for verdadeira.\n\nbreak = para o loop\ncontinue = pula para o próximo\nrange(n) = sequência de 0 a n-1",
     "code_example":"# FOR — para cada produto\nprodutos = ['Notebook', 'Mouse', 'Teclado']\nfor produto in produtos:\n    print(f'- {produto}')\n\n# FOR com range\nfor i in range(1, 6):  # 1, 2, 3, 4, 5\n    print(f'Parcela {i} de 5')\n\n# enumerate — índice + valor\nfor i, prod in enumerate(produtos, start=1):\n    print(f'{i}. {prod}')\n\n# WHILE — saque no caixa eletrônico\nsaldo = 1000.0\nwhile True:\n    valor = float(input('Saque (0 para sair): R$ '))\n    if valor == 0:\n        break\n    if valor > saldo:\n        print('Saldo insuficiente')\n        continue\n    saldo -= valor\n    print(f'Novo saldo: R$ {saldo:.2f}')",
     "real_world_case":"Processar CSV com 10.000 linhas, enviar email para cada cliente, verificar cada produto do estoque — tudo usa loops.",
     "best_practice":"Prefira 'for item in lista' ao 'for i in range(len(lista))'. Use enumerate() quando precisar do índice."},
   ],
   "exercises":[
    {"order":1,"difficulty":"facil","xp_reward":15,
     "title":"Classificador de IMC",
     "description":"Receba peso (kg) e altura (m). Calcule IMC = peso/altura² e classifique:\n- IMC < 18.5: Abaixo do peso\n- 18.5 a 24.9: Normal\n- 25 a 29.9: Sobrepeso\n- 30+: Obesidade",
     "hint":"Use elif para as faixas. IMC = peso / (altura ** 2)",
     "starter_code":"peso = float(input('Peso (kg): '))\naltura = float(input('Altura (m): '))\nimc = peso / (altura ** 2)\n# classifique e imprima\n",
     "solution_hint":"if imc < 18.5: c='Abaixo do peso'\nelif imc < 25: c='Normal'\nelif imc < 30: c='Sobrepeso'\nelse: c='Obesidade'\nprint(f'IMC: {imc:.1f} — {c}')"},
    {"order":2,"difficulty":"facil","xp_reward":15,
     "title":"Tabuada Automática",
     "description":"Peça um número e imprima a tabuada completa (1 a 10) formatada:\n```\n7 x  1 =   7\n7 x 10 =  70\n```",
     "hint":"Use for com range(1, 11). f'{i:2d}' reserva 2 espaços.",
     "starter_code":"n = int(input('Tabuada de: '))\nfor i in range(1, 11):\n    pass  # imprima cada linha formatada\n",
     "solution_hint":"n = int(input('Tabuada de: '))\nfor i in range(1, 11):\n    print(f'{n} x {i:2d} = {n*i:3d}')"},
    {"order":3,"difficulty":"medio","xp_reward":25,
     "title":"Validador de Senha",
     "description":"Crie validar_senha(senha) que retorne {'valida': bool, 'erros': list} com as regras:\n1. Mínimo 8 caracteres\n2. Pelo menos 1 maiúscula\n3. Pelo menos 1 número\n4. Pelo menos 1 especial (!@#$%)",
     "hint":"Use any(c.isupper() for c in senha). Crie lista de erros.",
     "starter_code":"def validar_senha(senha: str) -> dict:\n    erros = []\n    especiais = '!@#$%^&*'\n    # verifique cada regra\n    return {'valida': len(erros) == 0, 'erros': erros}\n\nprint(validar_senha('abc'))\nprint(validar_senha('Senha123!'))\n",
     "solution_hint":"def validar_senha(senha):\n    erros=[]\n    if len(senha)<8: erros.append('Mínimo 8 caracteres')\n    if not any(c.isupper() for c in senha): erros.append('Precisa de maiúscula')\n    if not any(c.isdigit() for c in senha): erros.append('Precisa de número')\n    if not any(c in '!@#$%^&*' for c in senha): erros.append('Precisa de especial')\n    return {'valida': not erros, 'erros': erros}"},
    {"order":4,"difficulty":"medio","xp_reward":25,
     "title":"Caixa Eletrônico",
     "description":"Simule um caixa eletrônico com saldo de R$ 1.000. O usuário pode sacar enquanto houver saldo. Valide que o valor é positivo e não ultrapassa o saldo.",
     "hint":"Use while True com break quando digitar 0. Use continue para pular saques inválidos.",
     "starter_code":"saldo = 1000.0\nprint(f'Saldo: R$ {saldo:.2f}')\nwhile True:\n    valor = float(input('\\nSaque (0 = sair): R$ '))\n    # implemente a lógica\n",
     "solution_hint":"while True:\n    valor=float(input('Saque (0=sair): R$ '))\n    if valor==0: print('Tchau!'); break\n    if valor<0: print('Valor inválido'); continue\n    if valor>saldo: print(f'Insuficiente. Disponível: R$ {saldo:.2f}'); continue\n    saldo-=valor; print(f'Saque de R$ {valor:.2f}. Saldo: R$ {saldo:.2f}')"},
    {"order":5,"difficulty":"dificil","xp_reward":35,
     "title":"Relatório de Vendas",
     "description":"Dada a lista abaixo, calcule:\n- Total, maior e menor venda\n- Média\n- Quantas acima da média\n- % de vendas acima de R$ 500\n\nvendas = [320, 850, 120, 1200, 450, 780, 90, 650, 430, 980]",
     "hint":"Calcule a média primeiro, depois use outro loop para contar as acima.",
     "starter_code":"vendas = [320, 850, 120, 1200, 450, 780, 90, 650, 430, 980]\n# calcule todas as métricas e imprima o relatório\n",
     "solution_hint":"total=sum(vendas);media=total/len(vendas)\nacima=sum(1 for v in vendas if v>media)\nacima500=sum(1 for v in vendas if v>500)\nprint(f'Total: R$ {total:,.2f}')\nprint(f'Maior: R$ {max(vendas):,.2f} | Menor: R$ {min(vendas):,.2f}')\nprint(f'Média: R$ {media:.2f}')\nprint(f'Acima da média: {acima} ({acima/len(vendas):.0%})')\nprint(f'Acima R$500: {acima500/len(vendas):.0%}')"},
   ],
  },
  {
   "order":3,"icon":"📦","color":"#06b6d4","xp_reward":100,
   "title":"Listas, Dicionários e Funções",
   "description":"As estruturas de dados mais usadas. Listas para sequências, dicionários para pares chave-valor (= JSON!), funções para código reutilizável.",
   "lessons":[
    {"order":1,"title":"Listas e List Comprehension","reading_minutes":8,
     "content":"Listas guardam múltiplos valores em ordem. São mutáveis e representam resultados de banco, itens de carrinho, listas de usuários...",
     "code_example":"produtos = ['Notebook', 'Mouse', 'Teclado']\n\n# Acesso\nprint(produtos[0])   # 'Notebook'\nprint(produtos[-1])  # 'Teclado' (último)\nprint(produtos[1:])  # ['Mouse', 'Teclado']\n\n# Modificação\nprodutos.append('Monitor')\nprodutos.remove('Mouse')\n\n# List comprehension\nprecos = [100, 250, 80, 400, 150]\ncom_desconto = [p * 0.9 for p in precos]\ncaros = [p for p in precos if p > 150]\n\nprint(com_desconto)  # [90.0, 225.0, 72.0, 360.0, 135.0]\nprint(caros)         # [250, 400]",
     "real_world_case":"Uma API retorna lista de produtos. Você filtra os em estoque, ordena por preço, retorna os 10 primeiros — tudo com lista + list comprehension.",
     "best_practice":"Prefira list comprehension a loops manuais para transformar/filtrar. Use sorted() para não modificar a lista original."},
    {"order":2,"title":"Dicionários: a estrutura mais importante","reading_minutes":9,
     "content":"Dicionários guardam pares chave:valor. São a estrutura mais importante do backend — JSON É um dicionário!",
     "code_example":"usuario = {\n    'nome': 'Ana Silva',\n    'email': 'ana@email.com',\n    'ativo': True\n}\n\n# Acesso seguro\nprint(usuario.get('fone'))      # None (sem erro)\nprint(usuario.get('fone', '')) # '' (default)\n\n# Iteração\nfor chave, valor in usuario.items():\n    print(f'{chave}: {valor}')\n\n# Lista de dicionários — resultado típico de banco\npedidos = [\n    {'id':1, 'produto':'Notebook', 'valor':2500.0, 'pago':True},\n    {'id':2, 'produto':'Mouse',    'valor':80.0,   'pago':False},\n]\n\npagos = [p for p in pedidos if p['pago']]\ntotal = sum(p['valor'] for p in pagos)\nprint(f'Recebido: R$ {total:.2f}')",
     "real_world_case":"Toda resposta de API REST é um dicionário (JSON). Webhook do Stripe chega como dicionário.",
     "best_practice":"Use .get() ao invés de [] quando a chave pode não existir — evita KeyError."},
    {"order":3,"title":"Funções: código reutilizável","reading_minutes":10,
     "content":"Funções encapsulam um bloco de código com um nome. Evitam repetição (DRY) e tornam o código testável.",
     "code_example":"# Type hints e docstring — boa prática\ndef calcular_desconto(preco: float, pct: float = 0.10) -> float:\n    \"\"\"Aplica desconto ao preço.\"\"\"\n    if preco <= 0:\n        raise ValueError('Preço deve ser positivo')\n    return preco * (1 - pct)\n\nprint(calcular_desconto(100))        # 90.0\nprint(calcular_desconto(100, 0.20))  # 80.0\n\n# Retornando múltiplos valores\ndef analisar(numeros: list) -> tuple:\n    return min(numeros), max(numeros), sum(numeros)/len(numeros)\n\nmenor, maior, media = analisar([10, 50, 30, 20])\n\n# Função de frete — caso real\ndef calcular_frete(cep: str, peso_kg: float) -> float:\n    tarifas = {'0':15,'1':15,'2':20,'3':20,'4':25,\n               '5':25,'6':30,'7':30,'8':35,'9':35}\n    base = tarifas.get(cep[0], 30)\n    return base + (peso_kg * 2.0)",
     "real_world_case":"calcular_imposto(), validar_cpf(), enviar_email(), formatar_endereco() — funções são o core da programação profissional.",
     "best_practice":"Uma função deve fazer UMA coisa. Sempre escreva docstring. Use type hints."},
   ],
   "exercises":[
    {"order":1,"difficulty":"facil","xp_reward":15,
     "title":"Lista de Compras",
     "description":"Implemente:\n- adicionar_item(lista, item)\n- remover_item(lista, item) → True/False\n- mostrar_lista(lista) → imprime numerada\n- total_itens(lista) → int",
     "hint":"Para remover, verifique 'if item in lista' antes de .remove().",
     "starter_code":"def adicionar_item(lista, item): pass\ndef remover_item(lista, item): pass\ndef mostrar_lista(lista): pass\ndef total_itens(lista): pass\n\ncompras = []\nadicionar_item(compras, 'Arroz')\nadicionar_item(compras, 'Feijão')\nmostrar_lista(compras)\n",
     "solution_hint":"def adicionar_item(l,i): l.append(i)\ndef remover_item(l,i):\n    if i in l: l.remove(i); return True\n    return False\ndef mostrar_lista(l):\n    for i,item in enumerate(l,1): print(f'{i}. {item}')\ndef total_itens(l): return len(l)"},
    {"order":2,"difficulty":"facil","xp_reward":15,
     "title":"Cadastro de Usuários",
     "description":"Crie:\n- criar_usuario(nome, email, idade) → dict com id automático e ativo=True\n- buscar_por_email(usuarios, email) → dict ou None\n- listar_ativos(usuarios) → lista",
     "hint":"Para buscar: use next() com generator expression.",
     "starter_code":"usuarios = []\ndef criar_usuario(nome, email, idade): pass\ndef buscar_por_email(usuarios, email): pass\ndef listar_ativos(usuarios): pass\n\nu1 = criar_usuario('Ana', 'ana@mail.com', 25)\nusers = [u1]\nprint(buscar_por_email(users, 'ana@mail.com'))\n",
     "solution_hint":"def criar_usuario(n,e,i): return {'id':1,'nome':n,'email':e,'idade':i,'ativo':True}\ndef buscar_por_email(u,e): return next((x for x in u if x['email']==e),None)\ndef listar_ativos(u): return [x for x in u if x['ativo']]"},
    {"order":3,"difficulty":"medio","xp_reward":25,
     "title":"Processador de Pedidos",
     "description":"Dado:\n```python\npedidos = [\n  {'id':1,'cliente':'Ana','itens':[{'produto':'Notebook','qtd':1,'preco':2500},{'produto':'Mouse','qtd':2,'preco':80}]},\n  {'id':2,'cliente':'Bob','itens':[{'produto':'Teclado','qtd':1,'preco':150}]},\n]\n```\nImplemente calcular_total(pedido) e relatorio_pedidos(pedidos).",
     "hint":"Total = sum(i['qtd'] * i['preco'] for i in pedido['itens'])",
     "starter_code":"pedidos = [\n  {'id':1,'cliente':'Ana','itens':[{'produto':'Notebook','qtd':1,'preco':2500},{'produto':'Mouse','qtd':2,'preco':80}]},\n  {'id':2,'cliente':'Bob','itens':[{'produto':'Teclado','qtd':1,'preco':150}]},\n]\ndef calcular_total(pedido): pass\ndef relatorio_pedidos(pedidos): pass\nrelatorio_pedidos(pedidos)\n",
     "solution_hint":"def calcular_total(p): return sum(i['qtd']*i['preco'] for i in p['itens'])\ndef relatorio_pedidos(ps):\n    for p in ps: print(f'#{p[\"id\"]} {p[\"cliente\"]}: R$ {calcular_total(p):,.2f}')"},
    {"order":4,"difficulty":"medio","xp_reward":25,
     "title":"Contador de Palavras",
     "description":"Crie:\n- contar_palavras(texto) → dict {palavra: frequência}\n- top_palavras(contagem, n=5) → lista das N mais frequentes\n\ntexto = 'Python é incrível. Python é usado em IA.'",
     "hint":"texto.lower(), substitua pontuação. dict.get() com default 0. sorted(..., key=lambda x: x[1], reverse=True)",
     "starter_code":"def contar_palavras(texto): pass\ndef top_palavras(contagem, n=5): pass\n\ntexto = 'Python é incrível. Python é usado em IA. Python é o futuro!'\nc = contar_palavras(texto)\nprint(top_palavras(c, 3))\n",
     "solution_hint":"def contar_palavras(t):\n    for p in '!,.;?': t=t.replace(p,'')\n    c={}\n    for w in t.lower().split(): c[w]=c.get(w,0)+1\n    return c\ndef top_palavras(c,n=5): return sorted(c.items(),key=lambda x:x[1],reverse=True)[:n]"},
    {"order":5,"difficulty":"dificil","xp_reward":35,
     "title":"Sistema de Estoque",
     "description":"Crie:\n- adicionar_produto(estoque, codigo, nome, qtd, preco)\n- vender(estoque, codigo, qtd) → (bool, mensagem)\n- relatorio(estoque) → tabela com alerta ⚠️ para qtd < 5\n- valor_total_estoque(estoque) → float\n\nestoque = {'P001': {'nome':..., 'qtd':..., 'preco':...}}",
     "hint":"Para vender: verifique se código existe e se qtd é suficiente.",
     "starter_code":"estoque = {}\ndef adicionar_produto(e,cod,nome,qtd,preco): pass\ndef vender(e,cod,qtd): pass\ndef relatorio(e): pass\n\nadicionar_produto(estoque,'P001','Notebook',10,2500.0)\nadicionar_produto(estoque,'P002','Mouse',3,80.0)\nprint(vender(estoque,'P001',2))\nrelatorio(estoque)\n",
     "solution_hint":"def adicionar_produto(e,c,n,q,p): e[c]={'nome':n,'qtd':q,'preco':p}\ndef vender(e,c,q):\n    if c not in e: return False,'Não encontrado'\n    if e[c]['qtd']<q: return False,f'Só {e[c][\"qtd\"]} disponíveis'\n    e[c]['qtd']-=q; return True,'Venda ok'\ndef relatorio(e):\n    for c,p in e.items():\n        al=' ⚠️' if p['qtd']<5 else ''\n        print(f'{c}: {p[\"nome\"]} | Qtd:{p[\"qtd\"]}{al} | R${p[\"preco\"]:.2f}')"},
   ],
  },
]
